version: '3.6'

services:
  league:
    image: postgres
    restart: on-failure
    container_name: league
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=league
    ports:
      - 15432:5432

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379